### ISSUE TITLE
Character tilted on X axis after ladder exit

### ISSUE THREAD

**Issue by exxxhumed** [ZiyaBahceci/ue5-ProceduralLadder#1]
First of all, let me tell you that this is a wonderful project and I love it. Thank you for your efforts.
I only seem to have a small issue of having the TPP character mesh now being tilted slightly on the X axis after exiting the top of the ladder. I am fairly new to Unreal and Blueprints so was unable to find a way to either reset this after the fact (looked into reset local axis but this wasn't helpful) or avoid it rotating at the top altogether.

Any help with this would be greatly appreciated!

**Comment by vengaunt** [comment]
> First of all, let me tell you that this is a wonderful project and I love it. Thank you for your efforts.
> I only seem to have a small issue of having the TPP character mesh now being tilted slightly on the X axis after exiting the top of the ladder. I am fairly new to Unreal and Blueprints so was unable to find a way to either reset this after the fact (looked into reset local axis but this wasn't helpful) or avoid it rotating at the top altogether.
> 
> Any help with this would be greatly appreciated!

Hi Exxxhumed,
I'll have a look and resolve the problem as soon as I leave the earthquake area. Thank you for reporting the problem!

**Comment by exxxhumed** [comment]
Oh my goodness, I hope you are well my friend. Forget my issue for now and focus on getting safe and back on your feet.

I wish you all the best!

**Comment by vengaunt** [comment]
> Oh my goodness, I hope you are well my friend. Forget my issue for now and focus on getting safe and back on your feet.
> 
> I wish you all the best!

No worries. I was there to provide logistics to my family. I'll be back in Istanbul before weekend. Thank you for your care!

**Comment by vengaunt** [comment]
> First of all, let me tell you that this is a wonderful project and I love it. Thank you for your efforts. I only seem to have a small issue of having the TPP character mesh now being tilted slightly on the X axis after exiting the top of the ladder. I am fairly new to Unreal and Blueprints so was unable to find a way to either reset this after the fact (looked into reset local axis but this wasn't helpful) or avoid it rotating at the top altogether.
> 
> Any help with this would be greatly appreciated!

Hi Exxhumed,

It appears so that the unwanted rotation happens when looking around. Now, upon exiting ladder, the player rotation should be normal.
